name: Lint

on:
  push:
    branches: [main, dev]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Tests
    uses: finki-hub/.github/.github/workflows/vitest.yaml@c545734f912fe47b9d24533e495471f4496cdf79
    with:
      test-args: ''

  tsc:
    uses: finki-hub/.github/.github/workflows/tsc.yaml@main
    secrets: inherit

  eslint:
    uses: finki-hub/.github/.github/workflows/eslint.yaml@main
    secrets: inherit
