name: Lint

on:
  push:
    branches: [main, dev]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Tests (Node 24)
    uses: finki-hub/.github/.github/workflows/vitest.yaml@main
    with:
      node-version: '24'
      test-args: ''

  tsc:
    uses: finki-hub/.github/.github/workflows/tsc.yaml@main
    secrets: inherit

  eslint:
    uses: finki-hub/.github/.github/workflows/eslint.yaml@main
    secrets: inherit
